spring.application.name=MVP
server.port=${SERVER_PORT:8080}

# Read connection properties from your local machine OS profile environments
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/zalex_hr}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.hikari.initialization.fail.timeout=1
spring.datasource.hikari.connection.timeout=30000